openapi: 3.0.3
info:
  title: Agentic RAG API
  description: FastAPI server for Agentic RAG system
  version: "1.0.0"

paths:
  /ask:
    post:
      summary: Query the Agentic RAG system
      operationId: ask_agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryRequest"
            example:
              query: "video rag"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResponse"
              example:
                answer: "WSO2 has AI-based products such as..."
  /:
    get:
      summary: Health check
      operationId: health_check
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                required:
                  - status
                  - message
              example:
                status: ok
                message: Agentic RAG API is running
components:
  schemas:
    QueryRequest:
      type: object
      properties:
        query:
          type: string
          description: User query for the Agentic RAG system
          example: "What are the AI-based products in WSO2?"
      required:
        - query
    QueryResponse:
      type: object
      properties:
        answer:
          type: string
          description: Answer generated by the Agentic RAG system
          example: "WSO2 has AI-based products such as..."
      required:
        - answer
